### ISSUE TITLE
Minecraft 1.20.2+

### ISSUE THREAD

**Issue by Logan9312** [HellBz/Forge-Server-Starter#1]
If you could update this to work with Minecraft 1.20.2 and higher versions that would be awesome, we're trying to play the latest pixelmon but it's hard to get the new curseforge updates on a server without this installer

**Comment by HellBz** [comment]
Look into it, next time

**Comment by HellBz** [comment]
Can you tell me, what is exactly not working with 1.20 or what is the Error @Logan9312

**Comment by HellBz** [comment]
Tested with latest 1.20.4 and works with my latest Version.

Push this version next time, is with improved autoinstaller, 
aswell a new System for detecting Internet-Connection and check for Version of the Script itself.
