### ISSUE TITLE
Generated .bat-files do not respect current .jar-file's name

### ISSUE THREAD

**Issue by xllifi** [HellBz/Forge-Server-Starter#4]
![image](https://github.com/HellBz/Forge-Server-Starter/assets/70767436/019d8e8c-a75b-43a9-a52d-dc6dae6e462e)

**Comment by HellBz** [comment]
Will look into this

**Comment by xllifi** [comment]
Either what I described, or they don't regenerate after the name has changed

**Comment by HellBz** [comment]
right now, the Name is hardcoded to minecraft_server.jar

but next time i can add this

**Comment by HellBz** [comment]
New 3.5.4 Respect the Current JAR-File-Name

Commit: [3.5.4 Version a - Start-Files respect current .jar-Name](https://github.com/HellBz/Forge-Server-Starter/commit/f258bb0985d702f194f6ee219e21cae04553ff87)
