### ISSUE TITLE
Cannot boot server when offline

### ISSUE THREAD

**Issue by Omicron166** [HellBz/Forge-Server-Starter#8]
Minecraft 1.20.1
Forge 47.3.0

I have a server folder with everything installed where I have already played multiple times (when online).

I tried to boot the server without an internet connection and I get a connection failed warning message and a "place the server jar in the folder" info message.

I've tried to put the vanilla server jar with different names but the same message keeps appearing.

I already have the server.properties configured with online-mode=false so making the server boot work is the only missing piece.

I know booting a minecraft server without an internet connection sound like a dumb idea but trust me, I have good reasons to do it.

**Comment by HellBz** [comment]
online-mode is just for Verifing Profiles, most time used in Hacked Clients, to save Money.
 
 But this is not a Part of my Tool, my Tool just download, Install and Start FORGE/NeoForge, nothing More.
 
 Is you not comletly sure, please remove all, and  leave just the JAR-File in the Folder from me.
 The Rest is guiding you trough the Install, then you can see all Folders and Files and modify them.

**Comment by voice-at-magicmirror** [comment]
Can confirm, it won't start without Internet connection, regardless of the online-mode setting. Tested on last available version 3.5.7
