### ISSUE TITLE
Cannot Parse Commands to Console

### ISSUE THREAD

**Issue by therealpro101** [HellBz/Forge-Server-Starter#9]
I looked at the description and saw that it said something about parsing ive tried to parse as i would normally and to no avail, the server will output the console but just cant interact with it.

![image](https://github.com/user-attachments/assets/9dcbbc35-50a3-442c-9fe8-8933de5b63ba)

![image](https://github.com/user-attachments/assets/2ae26bac-a525-4388-bf21-55f8c8c138e1)

**Comment by HellBz** [comment]
Because your Server is not fully Started, this is a part of FORGE / NeoForge not my Installer
